package net.wutnews.app.app.entiy;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import net.wutnews.app.app.entiy.GetNewsListData;

import net.wutnews.app.app.entiy.GetNewsListDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig getNewsListDataDaoConfig;

    private final GetNewsListDataDao getNewsListDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        getNewsListDataDaoConfig = daoConfigMap.get(GetNewsListDataDao.class).clone();
        getNewsListDataDaoConfig.initIdentityScope(type);

        getNewsListDataDao = new GetNewsListDataDao(getNewsListDataDaoConfig, this);

        registerDao(GetNewsListData.class, getNewsListDataDao);
    }
    
    public void clear() {
        getNewsListDataDaoConfig.getIdentityScope().clear();
    }

    public GetNewsListDataDao getGetNewsListDataDao() {
        return getNewsListDataDao;
    }

}
