package net.wutnews.app.app.entiy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GET_NEWS_LIST_DATA.
 */
public class GetNewsListData {

    private String id;
    private String post_title;
    private String post_src;
    private String post_excerpt;
    private String post_modified;
    private String post_type;
    private String post_link;
    private Boolean post_collect;
    private String term_id;
    private String thumb;

    public GetNewsListData() {
    }

    public GetNewsListData(String id, String post_title, String post_src, String post_excerpt, String post_modified, String post_type, String post_link, Boolean post_collect, String term_id, String thumb) {
        this.id = id;
        this.post_title = post_title;
        this.post_src = post_src;
        this.post_excerpt = post_excerpt;
        this.post_modified = post_modified;
        this.post_type = post_type;
        this.post_link = post_link;
        this.post_collect = post_collect;
        this.term_id = term_id;
        this.thumb = thumb;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPost_title() {
        return post_title;
    }

    public void setPost_title(String post_title) {
        this.post_title = post_title;
    }

    public String getPost_src() {
        return post_src;
    }

    public void setPost_src(String post_src) {
        this.post_src = post_src;
    }

    public String getPost_excerpt() {
        return post_excerpt;
    }

    public void setPost_excerpt(String post_excerpt) {
        this.post_excerpt = post_excerpt;
    }

    public String getPost_modified() {
        return post_modified;
    }

    public void setPost_modified(String post_modified) {
        this.post_modified = post_modified;
    }

    public String getPost_type() {
        return post_type;
    }

    public void setPost_type(String post_type) {
        this.post_type = post_type;
    }

    public String getPost_link() {
        return post_link;
    }

    public void setPost_link(String post_link) {
        this.post_link = post_link;
    }

    public Boolean getPost_collect() {
        return post_collect;
    }

    public void setPost_collect(Boolean post_collect) {
        this.post_collect = post_collect;
    }

    public String getTerm_id() {
        return term_id;
    }

    public void setTerm_id(String term_id) {
        this.term_id = term_id;
    }

    public String getThumb() {
        return thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    private GetNewsListDataSmeta smeta;

    public String getSmeta() {
        if (smeta != null){
            return smeta.getThumb();
        }else{
            return thumb;
        }

    }

    public void setSmeta(GetNewsListDataSmeta smeta) {
        this.smeta = smeta;
    }

}
